### ISSUE TITLE
at start 0,1 second splash screen and crush

### ISSUE THREAD

**Issue by ffdown** [XmYx/ainodes-pyside#11]
(ai-pixel) E:\AI\SD\ainodes-pyside>python frontend/main_app.py
Traceback (most recent call last):
  File "E:\AI\SD\ainodes-pyside\frontend\main_app.py", line 30, in <module>
    from frontend.mainwindow import MainWindow
ModuleNotFoundError: No module named 'frontend.mainwindow'

**Comment by XmYx** [comment]
Hi! Please try our new gui installer from https://github.com/XmYx/ainodes-installer ! : ) makes life, setup and model download a lot easier.
