### ISSUE TITLE
"Enter Event" every time i mouse over the image output area

### ISSUE THREAD

**Issue by LockMan007** [XmYx/ainodes-pyside#5]
"Enter Event" every time i mouse over the image output area

Not sure if that is intentional or not.

------------------------------------------------------------------------------------------------------------------------------------

Also, just tacking this on, (not expecting a resolution on this, i just have no other way to mention it) sometimes i get errors and have to restart aiNodes.
This is the last error I got.
I tried to generate a 1536 x 1152 on a EVGA 1080 ti FTW3 11gb.
I'm assuming it is a random error of something not loading right or something crashing or unloading, so I'll assume it is just something I have to tolerate.

Traceback (most recent call last):
  File "D:\2.0\backend\worker.py", line 70, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\2.0\frontend\ui_deforum.py", line 162, in run_deforum_six_txt2img
    self.deforum_six.run_deforum_six(W=int(params['W']),
  File "D:\2.0\backend\deforum\deforum_adapter.py", line 501, in run_deforum_six
    render_image_batch(args, prompts, root, image_callback=image_callback, step_callback=step_callback)
  File "D:\2.0\backend\deforum\six\render.py", line 130, in render_image_batch
    results = generate(args, root, step_callback=step_callback,)
  File "D:\2.0\backend\deforum\six\generate.py", line 227, in generate
    sampler = PLMSSampler(gs.models["sd"]) if args.sampler == 'plms' else DDIMSampler(gs.models["sd"])
  File "D:\2.0\ldm\models\diffusion\ddim.py", line 16, in __init__
    self.ddpm_num_timesteps = model.num_timesteps
AttributeError: 'NoneType' object has no attribute 'num_timesteps'

**Comment by XmYx** [comment]
Enter Event - yes, just a print, will get rid of it.
The next one will be resolved, it's just a method missing from vanilla ddim, for now, please use K-Samplers, they are much superior anyways. (K Euler A at ddim_eta 1.0 is the same as vanilla ddim if I'm correct)
Thanks

**Comment by LockMan007** [comment]
Thanks, you are an amazing person.
